version: '3.8'
services:
  packetstream:
    deploy:
      mode: replicated
      replicas: 10
      restart_policy:
        condition: on-failure
        max_attempts: 2
      resources:
        limits:
          cpus: "0.1"
          memory: '30M'
    image: packetstream/psclient:latest
    environment: 
      - CID=2MyD
      - http_proxy=http://194.226.139.224:9090
      - https_proxy=http://194.226.139.224:9090
    logging: 
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
